### ISSUE TITLE
Does not work!

### ISSUE THREAD

**Issue by NarayanSchuetz** [m1guelpf/swift-realtime-openai#1]
Not even the given example runs (XCode 16.0; iOS18). In fact it won't even compile like is but that is easily fixable, however, while the client connects sending a message results in a JSON error: `Error: keyNotFound(CodingKeys(stringValue: "audio", intValue: nil), Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "part", intValue: nil)], debugDescription: "No value associated with key CodingKeys(stringValue: \"audio\", intValue: nil) (\"audio\").", underlyingError: nil))`.

**Comment by m1guelpf** [comment]
Fixed the parsing error and updated the example code, thanks for reporting!
