### ISSUE TITLE
Conflicts with MacPaw OpenAI name

### ISSUE THREAD

**Issue by dashh5** [m1guelpf/swift-realtime-openai#2]
The name for this package is OpenAI, which conflicts with the Macpaw OpenAI swift community package, making them incompatible.

**Comment by m1guelpf** [comment]
These are fundamentally different APIs, so I didn't think the conflict mattered much. I'm open to different names if you have any suggestions!

**Comment by dashh5** [comment]
Love the project btw. I was working on implementing it myself but found the event structure to be a pain.. 

It may be worth addressing this conflict as I suspect I'm not the only one using multiple OpenAI services in the same app. Some suggestions would be:
- OpenAIRealtime
- OpenAI-Realtime
- Other permutations of this form. Thanks for considering!

**Comment by cerupcat** [comment]
Given this isn't officially from OpenAI, I would probably rename it to something that doesn't use that namespace directly.

**Comment by m1guelpf** [comment]
Seeing how MacPaw's client doesn't seem to be actively maintained (and OpenAI has no plans to release a Swift SDK at the moment) I'm leaning towards keeping the name. Might come back to this once I'm done building the library.

**Comment by cerupcat** [comment]
> Seeing how MacPaw's client doesn't seem to be actively maintained (and OpenAI has no plans to release a Swift SDK at the moment) I'm leaning towards keeping the name. Might come back to this once I'm done building the library.

That's fair, but for those that have had to change names due to conflicts like this, it's much better to create a unique name now when the library is young than in the future when there's more side effects to changing it.

Would re-consider and pick a name that doesn't insinuate this is OpenAI's official library.

**Comment by benvolioT** [comment]
PITA to use this library alongside the MacPaw library. Wish you'd reconsider.

**Comment by pannous** [comment]
Yeah source of confusion ;)

https://github.com/MacPaw/OpenAI/issues/276

**Comment by m1guelpf** [comment]
The package is now called `OpenAIRealtime`
