### ISSUE TITLE
Play output audio

### ISSUE THREAD

**Issue by day-dreaming-guy** [m1guelpf/swift-realtime-openai#4]
Hey! Thank you for the great library.
I noticed that the response is in audio output, but I only use the transcription to display the text. Is it possible to use the audio data to play it?

**Comment by m1guelpf** [comment]
You can access the `audio` property on an audio message, which contains the raw audio data. I'll be adding automatic handling for this to the `Conversation` class soon.

**Comment by mrmuke** [comment]
Hi! I have a question @m1guelpf, I've been trying to play the raw audio data but keep getting crackling sounds using swift's AVAudioPlayer. Have you had any luck playing it properly? Thanks.

**Comment by m1guelpf** [comment]
The library now includes capabilities for automatically playing back the audio once it's been completed (playing while streaming audio not supported yet). Just call the `startHandlingVoice()` method on a `Conversation`.
