### ISSUE TITLE
How to access the response audio data?

### ISSUE THREAD

**Issue by Zhou-Haowei** [m1guelpf/swift-realtime-openai#8]
Hi, thanks for the great job. I am confused about how to access the audio data after receving the responseAudioDone event. Are there any examples of how to do this?

**Comment by m1guelpf** [comment]
The library now includes capabilities for automatically playing back the audio once it's been completed (playing while streaming audio not supported yet). Just call the `startHandlingVoice()` method on a `Conversation`.
